// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeohlcbuepigawtqiyoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inplb2hsY2J1ZXBpZ2F3dHFpeW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NTU1MzEsImV4cCI6MjA1NzIzMTUzMX0.2xI6ngOMeDoB8fD2WMjP2pFiDbZ2p__xGRfZbGdPJZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);